---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 80

cloud:
  aws:
    dynamodb:
      endpoint: https://dynamodb.ap-northeast-2.amazonaws.com

dynamodb-region: ap-northeast-2
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    dynamodb:
      entity2ddl:
        auto: create
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1

server:
  port: 8081

cloud:
  aws:
    credentials:
      access-key: vr7lil
      secret-key: no579s
    dynamodb:
      endpoint: http://localhost:8000
    region: localhost